# Generated by Django 4.2.6 on 2025-05-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitySearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('search_count', models.PositiveIntegerField(default=1)),
                ('last_search', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'City Searches',
                'ordering': ['-search_count'],
            },
        ),
    ]
