WEATHER_CODES = {
    0: {"desc": "Ясно", "icon": "☀️"},
    1: {"desc": "Преимущественно ясно", "icon": "🌤"},
    2: {"desc": "Переменная облачность", "icon": "⛅"},
    3: {"desc": "Пасмурно", "icon": "☁️"},
    45: {"desc": "Туман", "icon": "🌫"},
    48: {"desc": "Depositing rime fog", "icon": "🌫"},
    51: {"desc": "Легкая морось", "icon": "🌧"},
    53: {"desc": "Умеренная морось", "icon": "🌧"},
    55: {"desc": "Сильная морось", "icon": "🌧"},
    56: {"desc": "Light freezing drizzle", "icon": "🌨"},
    57: {"desc": "Dense freezing drizzle", "icon": "🌨"},
    61: {"desc": "Небольшой дождь", "icon": "🌦"},
    63: {"desc": "Умеренный дождь", "icon": "🌧"},
    65: {"desc": "Сильный дождь", "icon": "🌧"},
    66: {"desc": "Light freezing rain", "icon": "🌨"},
    67: {"desc": "Heavy freezing rain", "icon": "🌨"},
    71: {"desc": "Slight snow", "icon": "❄️"},
    73: {"desc": "Moderate snow", "icon": "❄️"},
    75: {"desc": "Heavy snow", "icon": "❄️"},
    77: {"desc": "Snow grains", "icon": "❄️"},
    80: {"desc": "Ливень", "icon": "💧"},
    81: {"desc": "Сильный ливень", "icon": "💧"},
    82: {"desc": "Очень сильный ливень", "icon": "💧"},
    85: {"desc": "Slight snow showers", "icon": "🌨"},
    86: {"desc": "Heavy snow showers", "icon": "🌨"},
    95: {"desc": "Гроза", "icon": "⛈"},
    96: {"desc": "Гроза с градом", "icon": "⛈"},
    99: {"desc": "Heavy thunderstorm with hail", "icon": "⛈"},
}
